// design-sync の前段ビルド（cfg.buildCmd）。
//  1. Tailwind v4 で ds.css（= globals.css + html/body 補完）を .cache/ds.css にコンパイル
//  2. next/image shim が参照する小さな静的アセットを data URI にして .cache/assets.ts へ
// 出力はどちらも gitignore 済み。リポジトリ直下から `node .design-sync/prebuild.mjs` で実行する。
import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const require = createRequire(resolve(root, "package.json"));
const tailwind = require("@tailwindcss/postcss");
const postcss = require(
  require.resolve("postcss", {
    paths: [require.resolve("@tailwindcss/postcss")],
  }),
);

mkdirSync(resolve(here, ".cache"), { recursive: true });

// 1. CSS
const from = resolve(here, "ds.css");
const to = resolve(here, ".cache/ds.css");
const result = await postcss([
  tailwind({ base: root, optimize: false }),
]).process(readFileSync(from, "utf8"), { from, to });
writeFileSync(to, result.css);
console.error(
  `prebuild: css ${result.css.length} bytes -> .design-sync/.cache/ds.css`,
);

// 2. アセット（next/image shim が /public のパスを解決する）
// ブランドマークとパートナーのロゴ（計 260KB）。写真 jpg（19MB）は入れない。
const assets = { "/icons/mark.svg": "public/icons/mark.svg" };
for (const n of readdirSync(resolve(root, "public/images/partners"))) {
  if (n.endsWith(".png")) assets[`/images/partners/${n}`] = `public/images/partners/${n}`;
}
const map = {};
for (const [url, file] of Object.entries(assets)) {
  if (file.endsWith(".svg")) {
    map[url] = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(readFileSync(resolve(root, file), "utf8"))}`;
  } else {
    map[url] = `data:image/png;base64,${readFileSync(resolve(root, file)).toString("base64")}`;
  }
}
writeFileSync(
  resolve(here, ".cache/assets.ts"),
  `// generated by prebuild.mjs — do not edit\nexport const PUBLIC_ASSETS: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`,
);
console.error(
  `prebuild: ${Object.keys(map).length} asset(s) -> .design-sync/.cache/assets.ts`,
);

// 3. 型（.d.ts）。dist が無いので src/components から tsc の宣言だけを build/ts に出す。
//    コンバータは build/ts/index.d.ts を「公開 API」として読む（findTypesRoot の探索順）。
//    バレルはドット始まりでないパスに置く — ts-morph の glob はドットディレクトリを拾わない。
const compRoot = resolve(root, "src/components");
const walk = (d) => readdirSync(d).flatMap((n) => {
  const p = join(d, n);
  return statSync(p).isDirectory() ? walk(p) : /\.(tsx)$/.test(n) ? [p] : [];
});
const files = walk(compRoot).sort();
const barrel = files.map((f) => `export * from ${JSON.stringify("../../" + relative(root, f).replace(/\.tsx$/, ""))};`).join("\n") + "\n";
mkdirSync(resolve(root, "build/ds-entry"), { recursive: true });
writeFileSync(resolve(root, "build/ds-entry/index.ts"), barrel);
rmSync(resolve(root, "build/ts"), { recursive: true, force: true });
execFileSync(process.execPath, [resolve(root, "node_modules/typescript/bin/tsc"), "-p", resolve(here, "tsconfig.types.json")], { stdio: "inherit" });
writeFileSync(resolve(root, "build/ts/index.d.ts"), 'export * from "./build/ds-entry/index";\n');
console.error(`prebuild: ${files.length} component files -> build/ts (declarations)`);
